-- This is an empty migration.-- Add extension for safer enum alterations
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Alter the enum type
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTI_INFLAMMATORY_ANALGESICS';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTIBIOTIC';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTIFUNGAL';
ALTER TYPE "InventoryCategory" ADD VALUE 'DEWORMERS';
ALTER TYPE "InventoryCategory" ADD VALUE 'GASTROPROTECTORS_GASTROENTEROLOGY';
ALTER TYPE "InventoryCategory" ADD VALUE 'CARDIOLOGY';
ALTER TYPE "InventoryCategory" ADD VALUE 'DERMATOLOGY';
ALTER TYPE "InventoryCategory" ADD VALUE 'ENDOCRINOLOGY_HORMONAL';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANESTHETICS_SEDATIVES';
ALTER TYPE "InventoryCategory" ADD VALUE 'OTIC';
ALTER TYPE "InventoryCategory" ADD VALUE 'OINTMENTS';
ALTER TYPE "InventoryCategory" ADD VALUE 'RESPIRATORY';
ALTER TYPE "InventoryCategory" ADD VALUE 'OPHTHALMIC';
ALTER TYPE "InventoryCategory" ADD VALUE 'DRY_FOOD';
ALTER TYPE "InventoryCategory" ADD VALUE 'WET_FOOD';
ALTER TYPE "InventoryCategory" ADD VALUE 'CHIPS';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTI_EMETIC';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTISEPTICS_HEALING';
ALTER TYPE "InventoryCategory" ADD VALUE 'NEPHROLOGY';
ALTER TYPE "InventoryCategory" ADD VALUE 'ANTAGONISTS';
ALTER TYPE "InventoryCategory" ADD VALUE 'IMMUNOSTIMULANT';
ALTER TYPE "InventoryCategory" ADD VALUE 'APPETITE_STIMULANTS_HEMATOPOIESIS';
ALTER TYPE "InventoryCategory" ADD VALUE 'SUPPLEMENTS_OTHERS';