// Generated by https://quicktype.io

export interface BlogPostTitle {
    title:            string;
    slug:             Slug;
    mainImage:        MainImage;
    smallDescription: string;
    author:           string;
    _id:              string;
    _updatedAt:       string;
}

export interface MainImage {
    _type: string;
    asset: Asset;
}

export interface Asset {
}

export interface Slug {
    current: string;
    _type:   string;
}
